

import type { Ticket, Agent, DashboardStats } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'John Smith',
    email: 'john@helpdesk.com',
    status: 'online',
    tickets_assigned: 5,
    tickets_resolved: 142,
    avatar: '👨‍💼',
  },
  {
    id: 'agent-2',
    name: 'Sarah Johnson',
    email: 'sarah@helpdesk.com',
    status: 'online',
    tickets_assigned: 4,
    tickets_resolved: 156,
    avatar: '👩‍💼',
  },
  {
    id: 'agent-3',
    name: 'Mike Davis',
    email: 'mike@helpdesk.com',
    status: 'busy',
    tickets_assigned: 8,
    tickets_resolved: 128,
    avatar: '👨‍💼',
  },
  {
    id: 'agent-4',
    name: 'Emma Wilson',
    email: 'emma@helpdesk.com',
    status: 'away',
    tickets_assigned: 0,
    tickets_resolved: 134,
    avatar: '👩‍💼',
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 'TK-001',
    title: 'Login issue with two-factor authentication',
    description: 'Cannot login to account even with correct credentials. Two-factor authentication code is not being sent.',
    status: 'open',
    priority: 'high',
    category: 'Account',
    created_at: '2026-02-12T10:30:00',
    updated_at: '2026-02-12T10:30:00',
    assigned_to: null,
    customer_name: 'Alex Chen',
    customer_email: 'alex@customer.com',
  },
  {
    id: 'TK-002',
    title: 'Payment processing error',
    description: 'Getting error code 403 when trying to process payment. Order ID: ORD-12345',
    status: 'assigned',
    priority: 'urgent',
    category: 'Billing',
    created_at: '2026-02-12T09:15:00',
    updated_at: '2026-02-12T11:00:00',
    assigned_to: mockAgents[0],
    customer_name: 'Maria Rodriguez',
    customer_email: 'maria@customer.com',
  },
  {
    id: 'TK-003',
    title: 'Feature request: Dark mode',
    description: 'Would like to have a dark mode option in the application for better usability at night.',
    status: 'in-progress',
    priority: 'low',
    category: 'Feature Request',
    created_at: '2026-02-11T14:20:00',
    updated_at: '2026-02-12T08:00:00',
    assigned_to: mockAgents[1],
    customer_name: 'James Patterson',
    customer_email: 'james@customer.com',
  },
  {
    id: 'TK-004',
    title: 'Account deletion request',
    description: 'Customer wants to permanently delete their account and all associated data.',
    status: 'in-progress',
    priority: 'medium',
    category: 'Account',
    created_at: '2026-02-10T16:45:00',
    updated_at: '2026-02-12T07:30:00',
    assigned_to: mockAgents[2],
    customer_name: 'David Thompson',
    customer_email: 'david@customer.com',
  },
  {
    id: 'TK-005',
    title: 'Refund confirmation not received',
    description: 'Processed refund on 2026-02-08 but customer has not received confirmation email. Need to investigate.',
    status: 'resolved',
    priority: 'high',
    category: 'Billing',
    created_at: '2026-02-08T11:00:00',
    updated_at: '2026-02-12T12:00:00',
    assigned_to: mockAgents[0],
    customer_name: 'Lisa Anderson',
    customer_email: 'lisa@customer.com',
    resolution_time: 25,
  },
  {
    id: 'TK-006',
    title: 'Mobile app crashes on startup',
    description: 'Application crashes immediately upon launching on iOS 18. Verified on iPhone 15 Pro.',
    status: 'open',
    priority: 'urgent',
    category: 'Bug',
    created_at: '2026-02-12T12:30:00',
    updated_at: '2026-02-12T12:30:00',
    assigned_to: null,
    customer_name: 'Robert Kumar',
    customer_email: 'robert@customer.com',
  },
];

export const mockDashboardStats: DashboardStats = {
  total_tickets: 247,
  open_tickets: 45,
  pending_tickets: 28,
  resolved_tickets: 174,
  average_resolution_time: 18, 
  agent_capacity: 65, 
};
